config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('seller/', include('seller.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name='order'
urlpatterns = [   
    path('order_detail/<int:pk>/', views.order_detail, name='order_detail'),
    path('modify_cart/', views.modify_cart, name='modify_cart'),
    ]

seller/urls.py
from django.urls import path
from . import views

app_name='seller'
urlpatterns = [   
    path('', views.seller_index, name='seller_index'),
    path('add_food/', views.add_food, name='add_food'),
    path('food_detail/<int:pk>/', views.food_detail, name='food_detail'),
    path('food_delete/<int:pk>/', views.food_delete, name='food_delete'),
    ]

order/models.py
from django.db import models
from seller.models import Food
from django.contrib.auth.models import User
# Create your models here.

# 어떤 음식을 얼마나 카트에 담았나?

# table 생성 default 이름 : customer_cart
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.DO_NOTHING)
    amount = models.IntegerField(default=0)

seller/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class Category(models.Model):
#     name = models.CharField(max_length=200)

class Food(models.Model):
    # id
    user=models.ForeignKey(User, on_delete=models.CASCADE) # 상품 판매자
    name=models.CharField(max_length=20)
    price = models.IntegerField()
    description=models.TextField()
    image_url=models.URLField()

    def __str__(self) -> str:
        return self.name

config/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy
from seller.models import Food
def index(request):
    object_list = Food.objects.all()
    context = {
        'object_list':object_list
    }
    return render(request, 'home.html',context)

class UserCreateView(CreateView):
    template_name='registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name='registration/register_done.html'

order/views.py
from django.shortcuts import render
from seller.models import Food
from .models import Cart
from django.db.models import Sum
# Create your views here.
def order_detail(request, pk):
    food = Food.objects.get(pk=pk)
    context = {
        'object':food
    }
    return render(request, 'order/order_detail.html', context)

from django.http import JsonResponse
def modify_cart(request):
    # A사용자가 카트에 담은 B음식에 대해서 수량을 조정하는 내용
    # 응답 : 새롭게 변경된 수량, 전체 카트 음식 수량
    # 어떤 사용자?
    user = request.user
    # 어떤 음식?
    food_id = request.POST['foodId']
    food = Food.objects.get(pk=food_id)
    # 카트 정보
    cart, created = Cart.objects.get_or_create(food=food, user=user)
    # 수량 업데이트
    cart.amount += int(request.POST['amountChange'])
    if cart.amount>0:
        cart.save()
    # "user"가 카트에 담은(cart)한 전체 음식(개별 개수 amount) 개수
    # Qusetion - Choice
    # 이 문제에 대한 초이스
    # question.choice_set
    totalQuantity = user.cart_set.aggregate(totalcount=Sum('amount'))['totalcount']
    # Json
    context = {
        'newQuantity' : cart.amount,
        'totalQuantity' : totalQuantity,
        'message':'성공',
        'success':True
    }
    return JsonResponse(context)

seller/views.py
from django.shortcuts import render, redirect
from .models import Food
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

# Create your views here.
# 자신이 판매하는 상품 리스트를 보여주기
# -> 전체 Food에서 특정 user(판매자)인 food만 가져온다.
# -> 전체 Food에서 내가 올린 food만 filter한다.
# Food.objects.all().filter(조건)
# 상품 등록 기능

@login_required
def seller_index(request):
    foods = Food.objects.filter(user=request.user)
    context={
        'object_list': foods
    }
    return render(request, 'seller/seller_index.html', context)

@login_required
def add_food(request):
    # get
    if request.method=='GET':
        return render(request, 'seller/seller_add_food.html')
    # post
    elif request.method=="POST":
        # 폼에서 전달되는 각 값을 뽑아와서 DB에 저장

        # Food 내용을 구성 영역
        # category = Category.objects.get(name=request.POST['category'])
        user=request.user
        food_name = request.POST['name']
        food_price = request.POST['price']
        food_description = request.POST['description']

        # 이미지 저장 및 url 설정 내용
        fs=FileSystemStorage()
        uploaded_file = request.FILES['file']
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)

        Food.objects.create(user= user,name=food_name, price =food_price , description=food_description,image_url=url)    

        # food_name, price, description
        return redirect('seller:seller_index')

@login_required
def food_detail(request, pk): # detail 화면은 pk를 받아야 되고, object(하나의 데이터 덩어리, 자장면 하나)를 전달
    object = Food.objects.get(pk=pk)
    context = {
        'object':object
    }
    return render(request, 'seller/seller_food_detail.html', context)

@login_required
def food_delete(request, pk):
    object = Food.objects.get(pk=pk)
    object.delete()
    return redirect('seller:seller_index')

order/templates/order/order_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- 변경영역 -->
<div>
    <a href="#" class="btn btn-primary">
    장바구니 <span class="badge bg-secondary"><span id="totalQuantity"></span></span>
</a>
</div>
<!-- 변경영역 -->
<div class="container mt-5">
<div class="row">
<div class="col-md-6">
    <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image">
</div>
<div class="col-md-6 info-section">
    <h2>{{ object.name }}</h2>
    <h3 class="text-muted">{{ object.price }}원</h3>
    <p>{{ object.description }}</p>
</div>
</div>
</div>
<div  class="container">
<input type="hidden" id="csrfToken" value="{{csrf_token}}">
<button type="button" onclick="modifyCartAmount({{object.id}}, 1)" class="btn btn-danger">담기</button>
<button type="button" onclick="modifyCartAmount({{object.id}}, -1)" class="btn btn-success">빼기</button>
<button type="button" class="btn btn-primary">
선택수량 <span class="badge bg-secondary"><span id="currentQuantity"></span></span>
</button>
</div>

<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

<script>
function getCsrfToken(){
return document.getElementById('csrfToken').value;
}
function modifyCartAmount(food_id, change){
var xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "order:modify_cart" %}', true); // 확인 : 이전 -> customer:modify_cart
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRFToken', getCsrfToken());

    xhr.onload = function() {
        if (this.status === 200) {
            var response = JSON.parse(this.responseText);
            document.getElementById('currentQuantity').textContent = response.newQuantity;
            
            document.getElementById('totalQuantity').textContent = response.totalQuantity;// 추가
         
            console.log('Update successful:', response.message);
        } else {
            console.error('Error updating:', this.statusText);
        }
    };

    xhr.send(`foodId=${food_id}&amountChange=${change}`);
}
</script>
{% endblock %}

seller/templates/seller/seller_add_food.html
{% extends 'base.html' %}

{% block content %}
<h1>{{user}} 님의 상품 등록 페이지</h1>

<form action="" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}
    <div class="row g-3 mb-3">       
        <div class="col-md-4">
            <label for="name" class="form-label">음식이름:</label>
            <input type="text" name="name" class="form-control" id="name">
        </div>
        <div class="col-md-4">
            <label for="price" class="form-label">가격:</label>
            <input type="number" name="price" class="form-control" id="price">
        </div>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">소개:</label>
        <textarea name="description" rows="2" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">사진을 올려주세요</label>
        <input type="file" name="file" class="form-control" id="file">
    </div>
    <div class="text-center">
        <input type="submit" value="제출" class="btn btn-success">
    </div>
</form>
{% endblock %}

seller/templates/seller/seller_food_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image">
        </div>
        <div class="col-md-6 info-section">
            <h2>{{ object.name }}</h2>
            <h3 class="text-muted">{{ object.price }}원</h3>
            <p>{{ object.description }}</p>

            <form action="{% url 'seller:food_delete' pk=object.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="삭제하기" class="btn-custom">
            </form>
        </div>
    </div>
</div>
{% endblock %}

seller/templates/seller/seller_index.html
{% extends 'base.html' %}
{% block extra-style %}
<style>
.food-image {
    width: 100%;   /* 이미지를 카드의 너비에 맞춤 */
    height: 200px; /* 이미지의 높이를 200px로 고정 */
    object-fit: cover; /* 이미지 비율을 유지하면서 해당 영역을 완전히 채움 */
}
</style>
{% endblock %}
{% block content %}
<h1>{{user}}의 샵입니다!</h1>

<div class="row">
    <div class="col-md-6">
        <h3>음식</h3>
        <div class="row">

        {% for food in object_list %}
            <div class="col-sm-6 col-md-4 mb-4">
                <div class="card">
                    <a href="{% url 'seller:food_detail' pk=food.id %}">
                        <img src="{{ food.image_url }}" class="card-img-top food-image" alt="{{ food.name }}">
                        <div class="card-body row">
                            <h5 class="card-title">{{ food.name }}</h5>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>

    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'seller:add_food' %}" class="btn btn-primary">제품 등록</a>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} 멋사 반점 {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            height: 100%;
        }

        .main-content {
            flex: 1;
        }
        footer {
            padding: 30px 0;
            background: #f7f7f7;
        }
        .content-padding {
            padding: 0 100px 0 100px;
        }
    </style>
    {% block extra-style %}{% endblock %}
</head>

<body>
    <div class="wrapper">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}" style="font-weight: bold; font-style: italic;">멋사 반점</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">대표메뉴</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">고객게시판</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:seller_index' %}">판매자 페이지</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Util
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="">Admin</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Search</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item dropdown">
                        {% if user.is_active %}
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarUserDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>&nbsp;{% firstof user.get_short_name user.get_username %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarUserDropdown">
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Logout</button>
                            </form>
                            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                        </ul>
                        {% else %}
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarAnonymousDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>&nbsp;Anonymous
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarAnonymousDropdown">
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                        </ul>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="main-content">
        {% block content %}{% endblock %}
    </div>

    {% block footer %}
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
            <p>© 2024 재밌는 장고 공부. 모든 권리 보유.</p>
            <p>Follow us: <a href="#">Facebook</a> | <a href="#">Twitter</a> | <a href="#">Instagram</a></p>
            <p>개인정보처리방침 | 이용약관</p>
        </div>
    </footer>
    {% endblock %}
    <script src="https://kit.fontawesome.com/c998a172fe.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra-script %}{% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block extra-style %}
<style>
.food-image {
    width: 100%;   /* 이미지를 카드의 너비에 맞춤 */
    height: 200px; /* 이미지의 높이를 200px로 고정 */
    object-fit: cover; /* 이미지 비율을 유지하면서 해당 영역을 완전히 채움 */
}
</style>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <h3>음식</h3>
        <div class="row">

        {% for food in object_list %}
            <div class="col-sm-6 col-md-4 mb-4">
                <div class="card">
                    <a href="{% url 'order:order_detail' pk=food.id %}">
                        <img src="{{ food.image_url }}" class="card-img-top food-image" alt="{{ food.name }}">
                        <div class="card-body row">
                            <h5 class="card-title">{{ food.name }}</h5>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>
</div>
{% endblock %}